### PR TITLE
Made `TemporalWorker.ExecuteAsync()` keep working even after `Dispose()`.

### LINKED ISSUE #500: [Bug] Segfault/crash occurs when using tasks without await
### Describe the bug

Replication that can be in a test case with access to a `Client`:

```csharp
    [Workflow]
    public class CustomFuncWorkflow
    {
        private readonly Func<Task> func;

        public CustomFuncWorkflow(Func<Task> func) => this.func = func;

        [WorkflowRun]
        public Task RunAsync() => func();
    }

    [Fact]
    public async Task CauseSegfault()
    {
        await RunInWorkflowAsync(
            new($"tq-{Guid.NewGuid()}"),
            async () => { /*do nothing*/ });
    }

    private Task<WorkflowHandle> RunInWorkflowAsync(TemporalWorkerOptions workerOptions, Func<Task> func)
    {
        workerOptions.AddWorkflow(WorkflowDefinition.Create(
            typeof(CustomFuncWorkflow),
            null,
            _args => new CustomFuncWorkflow(func)));
        using var worker = new TemporalWorker(Client, workerOptions);
        return worker.ExecuteAsync(async () =>
        {
            var handle = await Client.StartWorkflowAsync(
                (CustomFuncWorkflow wf) => wf.RunAsync(),
                new($"wf-{Guid.NewGuid()}", workerOptions.TaskQueue!));
            await handle.GetResultAsync();
            return handle as WorkflowHandle;
        });
    }
```

Can give different forms of segfault/crash issues from hard crash to something like this:
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at Temporalio.Bridge.Interop.Methods.worker_poll_workflow_activation(Temporalio.Bridge.Interop.Worker*, Void*, IntPtr)
--------------------------------
   at Temporalio.Bridge.Worker+<PollWorkflowActivationAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Temporalio.Bridge.Worker.PollWorkflowActivationAsync()
   at Temporalio.Worker.WorkflowWorker+<ExecuteAsync>d__10.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.__Canon ByRef)
   at Temporalio.Worker.WorkflowWorker.ExecuteAsync()
   at Temporalio.Worker.TemporalWorker+<ExecuteInternalAsync>d__35.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OutputWaitEtwEvents>b__12_0(System.Action, System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action, Boolean)
   at System.Threading.Tasks.Task.RunContinuations(System.Object)
   at System.Threading.Tasks.Task.FinishContinuations()
   at System.Threading.Tasks.Task`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].TrySetResult(System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].SetExistingTaskResult(System.Threading.Tasks.Task`1<System.Threading.Tasks.VoidTaskResult>, System.Threading.Tasks.VoidTaskResult)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult()
   at Temporalio.Bridge.Worker+<ValidateAsync>d__13.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].ExecutionContextCallback(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext(System.Threading.Thread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1+AsyncStateMachineBox`1[[System.Threading.Tasks.VoidTaskResult, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter+<>c.<OutputWaitEtwEvents>b__12_0(System.Action, System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+ContinuationWrapper.Invoke()
   at System.Threading.Tasks.AwaitTaskContinuation.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

But strangely if you change `RunInWorkflowAsync` to be `async` and change its `return` to `return await` the problem goes away. There is something in the worker execute code or interop code or something that does not have proper lifetime for the worker `ExecuteAsync` body.

### PR DESCRIPTION
**Pull request by maciejdudko**
## What was changed
Changed how resources are disposed inside `TemporalWorker`. If `ExecuteAsync` is called, then the `Dispose` method does nothing and instead the resources are disposed at the end of `ExecuteAsync`. If it's not called, then resources are disposed with `Dispose` call as normal.

## Why?
Fixes crash that happens if `TemporalWorker` is disposed too early.

## Checklist

1. Closes #500

2. How was this tested:
Added testcase `WorkflowWorkerTests.ExecuteWorkflowAsync_PrematureDispose_WorkflowCompletes`

### CODE REVIEW

File: src/Temporalio/Worker/TemporalWorker.cs [hunk 1]
```diff
@@ -261,16 +281,10 @@ public void Dispose()
         /// <param name="disposing">Whether disposing.</param>
         protected virtual void Dispose(bool disposing)
         {
-            if (disposing)
+            var disposer = Interlocked.Exchange(ref this.disposer, null);
```
Comment (cretz) [inline src/Temporalio/Worker/TemporalWorker.cs]: Should we not do this unless `disposing` is true? I guess it doesn't matter much, but it is a bit confusing to read

File: src/Temporalio/Worker/TemporalWorker.cs [hunk 2]
```diff
@@ -282,6 +296,13 @@ private async Task ExecuteInternalAsync(
                 throw new InvalidOperationException("Already started");
             }
 
+            // Take ownership of the disposer to make sure the workers aren't disposed before completion of this function
+            using var disposer = Interlocked.Exchange(ref this.disposer, null);
```
Comment (cretz) [inline src/Temporalio/Worker/TemporalWorker.cs:299]: I believe I have confirmed that even in this situation:

```csharp
public Task StartWorkerAsync()
{
    using var worker = new TemporalWorker(someOptions);
    // Note this does not take the disposer because code is not run
    // inside of this because it is "async" so it waits for first "await"
    return worker.ExecuteAsync(someToken);
    // worker is disposed here
}

var task = StartWorkerAsync();
await task;
```

The disposer is properly transfered _before_ the `ExecuteAsync` call is returned. But yes it will be important for future SDK devs to make sure no yieldable await points are ever added before this line is called. Technically we can help with this by doing this in the outer `ExecuteAsync` calls and removing the `async` keyword from them, but I am fine with this too.

File: tests/Temporalio.Tests/Worker/WorkflowWorkerTests.cs [hunk 3]
```diff
@@ -7615,12 +7634,16 @@ private async Task<TResult> ExecuteWorkerAsync<TWorkflow, TResult>(
...
         IWorkerClient? client = null)
     {
-        options ??= new();
-        options = (TemporalWorkerOptions)options.Clone();
+        options = PrepareOptions<TWorkflow>((TemporalWorkerOptions?)options?.Clone() ?? new());
+        using var worker = new TemporalWorker(client ?? Client, options);
+        return await worker.ExecuteAsync(() => action(worker));
+    }
+
+    private static TemporalWorkerOptions PrepareOptions<TWorkflow>(TemporalWorkerOptions options)
```
Comment (cretz) [inline tests/Temporalio.Tests/Worker/WorkflowWorkerTests.cs]:
```suggestion
    private static TemporalWorkerOptions PrepareWorkerOptions<TWorkflow>(TemporalWorkerOptions options)
```

Pedantic, don't have to change

**Review by cretz — APPROVED** [review]
Looks good, nothing blocking (comments are mostly unimportant)
