### PR TITLE
Fix issue with search attribute keyword list type

### LINKED ISSUE #526: [Bug] KeywordList cannot be resolved as part of WorkflowExecutionDescription
### What are you really trying to do?

I am trying to get a value of a custom search attribute of a `KeywordList` type once the workflow is completed.

### Describe the bug

When executing a code as following, the `TryGetValue` returns `false` even the value is there, but of a `List<object>` type.

```
var description = await workflowHandle.DescribeAsync();

if (description.TypedSearchAttributes.TryGetValue(MySearchAttributes.PetNames, out var petNames))
{}
```

### Minimal Reproduction

Can be found in this commit: https://github.com/temporalio/samples-dotnet/commit/9c72c609b02578209749b661535518c869118bff

### Environment/Versions

- OS and processor: M4 Mac
- Temporal Version: 1.7.0, 1.8.0
- Are you using Docker or Kubernetes or building Temporal from source? No

### PR DESCRIPTION
**Pull request by cretz**
## What was changed

* Made sure all representations of search attribute keyword list values (coming from user or deserialized from server) are `List<string>`
* Fixed tests to start including search attribute keyword lists (it was marked as a TODO because older dev server didn't support them on start)

## Checklist

1. Closes #526

### CODE REVIEW

File: src/Temporalio/Common/SearchAttributeCollection.cs [hunk 1]
```diff
@@ -41,9 +41,12 @@ public class SearchAttributeCollection : IReadOnlyCollection<SearchAttributeKey>
...
-        /// <param name="values">The values that are actually used. Warning, this is not copied.
-        /// </param>
-        internal SearchAttributeCollection(SortedDictionary<SearchAttributeKey, object> values) =>
+        internal SearchAttributeCollection()
+            : this(new())
+        {
+        }
+
+        private SearchAttributeCollection(SortedDictionary<SearchAttributeKey, object> values) =>
             this.values = values;
```
Comment (maciejdudko) [inline src/Temporalio/Common/SearchAttributeCollection.cs:50]: Nit: the private constructor is only used once, in the internal constructor. It can be removed and initialization can be done directly in the internal constructor (or even better, inline in the field declaration).

**Review by maciejdudko — APPROVED** [review]
Looks good! I left one minor suggestion. LGTM!

File: src/Temporalio/Common/SearchAttributeCollection.cs (hunk 1 above)
Comment (cretz) [reply src/Temporalio/Common/SearchAttributeCollection.cs:50]: This private constructor is also used in `FromProto` and `ToSearchAttributeCollection`
