### PR TITLE
Handle errors with update result serialization

### LINKED ISSUE #465: [Bug] Update result serialization failure silently swallowed
### Describe the bug

Due to how update chose to use `task.ContinueWith` (maybe not the best idea in #142), when an exception occurs in update result serialization, it is swallowed. We need to make sure to surface this as a failure likely following the same rules as regular update failure (so for most it'll be a task failure).

### PR DESCRIPTION
**Pull request by cretz**
## What was changed

Previously we swallowed failures to serialize update results. Now we will fail the update or the task depending on the error.

## Checklist

1. Closes #465

### CODE REVIEW

File: src/Temporalio/Worker/WorkflowInstance.cs [hunk 1]
```diff
@@ -1185,49 +1185,73 @@ private Task ApplyDoUpdateAsync(DoUpdate update)
                 return task.ContinueWith(
                     _ =>
                     {
-                        inProgressHandlers.Remove(inProgress);
```
Comment (cretz) [inline src/Temporalio/Worker/WorkflowInstance.cs:1188]: The PR makes this a bit ugly, I recommend "hide whitespace" in the this diff view (i.e. https://github.com/temporalio/sdk-dotnet/pull/468/files?diff=unified&w=1)

File: tests/Temporalio.Tests/Worker/WorkflowWorkerTests.cs [hunk 2]
```diff
@@ -3081,7 +3081,7 @@ public class DynamicHandlersWorkflow
         [WorkflowRun]
         public Task RunAsync() => Workflow.WaitConditionAsync(() => false);
 
-        [WorkflowSignal]
+        [WorkflowUpdate]
```
Comment (cretz) [inline tests/Temporalio.Tests/Worker/WorkflowWorkerTests.cs:3084]: This is to fix a mostly-unrelated flake where slow GH runners were not guaranteeing signal order as the test expected

**Review by Sushisource — APPROVED** [review]
